// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agennmpmizazbapvqkqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnZW5ubXBtaXphemJhcHZxa3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODkxMjksImV4cCI6MjA2MTE2NTEyOX0.k1hZTLzco6zFXgngGIBazVxjywWeRTyV81FXZAq9hmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);